iamclient/iamclient.go, iamclient/iamclient_test.go
=> Use subjects instead of users

logging/archivator.go, logging/logging.go, logging/logging_test.go
=> [logging] Getting instance logs implementation

config/config.go, config/config_test.go
=> [config] Replace config.Duration to aostypes.Duration 

launcher/launcher.go
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
=> [launcher] Remove preallocated slices if size is not determined

monitoring/monitoring_internal_test.go
=> [all] Replace config.Duration to aostypes.Duration

launcher/launcher.go, launcher/launcher_test.go, monitorcontroller/monitorcontroller.go, monitorcontroller/monitorcontroller_test.go
=> Use resourcemanager from aos_common

servicemanager/image.go, servicemanager/servicemanager_test.go
=> Revert remove blobs directory

launcher/launcher_test.go, launcher/spec.go
=> [launcher] Append aos envvars to default oci runtime spec

networkmanager/networkmanager.go, networkmanager/networkmanager_test.go
=> Add rule to accept traffic in  FORWARD chain

servicemanager.go
=> [main] Remove board config file on --reset command

networkmanager/resolvehosts.go
Signed-off-by: Mykola Solianko <mykola.solianko@icomera.com>
=> [networkmanager] Fix hosts file permisions

launcher/instance.go, launcher/launcher.go
=> [launcher] Add instance id to start, stop logs

launcher/launcher.go
=> [launcher] Change order of start stop instance monitoring

runner/runner.go
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
=> [runner] Add instance id to stop log and change `service` to `instance`

launcher/launcher.go
=> [luncher] Fix double start instance monitor

launcher/launcher.go, launcher/service.go, servicemanager/servicemanager.go, servicemanager/servicemanager_test.go
=> [launcher] Fix deadlock with failed instanes

runner/aos-service@.service
This reverts commit 65fb3c97dbec2391d90742f7de3935444197be9e.
=> Revert "[runner] Make instance systemd units to start before SM"

aos_servicemanager.cfg, config/config.go, config/config_test.go, iamclient/iamclient.go, iamclient/iamclient_test.go
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
=> [config] Update server URL's to have same format for all Aos components

smclient/smclient.go
=> [smclient] Fix call update unit config

launcher/launcher.go
=> [launcher] Add hosts to instance /etc/hosts from SM config

servicemanager.go
=> [main] Do not use traffic monitore in case of runx runner

go.mod, go.sum, vendor/github.com/aoscloud/aos_common/resourcemonitor/resourcemonitor.go, vendor/github.com/bwesterb/go-xentop/.gitignore, vendor/github.com/bwesterb/go-xentop/LICENSE, vendor/github.com/bwesterb/go-xentop/README.md, vendor/github.com/bwesterb/go-xentop/xentop.go, vendor/modules.txt
=> [vendor] Update aos_common

_integration/logging_test/logging_test.go
=> [integration_test] Fix logging test according new API

database/database.go, database/database_internal_test.go, networkmanager/networkmanager.go, networkmanager/networkmanager_test.go
This PR is a cherry-pick from the main branch
=> [networkmanager] Save vlan interface name in DB

alerts/alerts.go, alerts/alerts_test.go, servicemanager.go, smclient/smclient.go, smclient/smclient_test.go
It is required to resolve cyclic deps for other packages
=> [alerts] Revert deleted alerts package
